FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY flights.csv .
COPY train_model.py .
COPY prediction_service.py .

RUN python train_model.py

EXPOSE 8000

CMD ["uvicorn", "prediction_service:app", "--host", "0.0.0.0", "--port", "8000"]